function [fitresult, gof] = createFit(x, t)
%CREATEFIT(X,T)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : x
%      Y Output: t
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 21-May-2021 23:49:54


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( x, t );

% Set up fittype and options.
ft = fittype( 'poly1' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 't vs. x', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel погода
ylabel t
grid on


